name: generate animation

on:
  # 매일 자동으로 실행
  schedule:
    - cron: "0 */24 * * *"
  
  # 수동으로 워크플로를 실행할 수 있도록 설정
  workflow_dispatch:
  
  # master 브랜치에 푸시할 때마다 실행
  push:
    branches:
    - master
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # GitHub 사용자(KimuJinsu)의 기여 그래프에서 뱀 게임을 생성하고, SVG 애니메이션을 출력합니다.
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: KimuJinsu
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 생성된 SVG 파일을 output 브랜치로 푸시합니다.
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
