name: generate animation

on:
  schedule:
    - cron: "0 */24 * * *"  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: KimuJinsu
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=#FF4500&color_dots=#1f77b4,#aec7e8,#ff7f0e,#ffbb78,#2ca02c

      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          add: 'dist/*'
          message: 'Generated snake with custom colors'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
